### PR TITLE
Virtual debit card

### PR DESCRIPTION
**Pull request by viditvarshney**
THis is a web based project , this code generates a virtual debit card with name of yours and a CVV number on it ... the best part of this is .. CVV number changes every time when you run the code

### CODE REVIEW

**Review by divyanshu-rawat — APPROVED** [review]
LGTM!

**Comment by viditvarshney** [comment]
thanks 🙏

https://www.github.com/viditvarshney

**Comment by divyanshu-rawat** [comment]
@Paarmita 
can you please review it 👍

**Comment by viditvarshney** [comment]
excuse me why my code is not merged yet?

**Comment by divyanshu-rawat** [comment]
@viditvarshney I have reviewed your code and it looks good to me, but it doesn't mean that it looks good to other contributors and community members as well.
So, I am waiting for other community members to review it as well.
Good Luck 👍 

@yashovardhanagrawal, can you go through the code and review and see whether it's good to merge. 👍

**Comment by theamanbhargava** [comment]
Looks good to me too.

**Review by sunilsj99 — APPROVED** [review]
Looks fine to me as well !!

**Pull request merged**
